# DataFrame Methods(Operations)
- df.head(n) : print n rows of data (by defualt 5 rows if n is missing)
- df.tail(n) : print n rows of data (by defualt 5 rows if n is missing)
- df.sample(n) : print each time n random row of the data (by default 1 row if n is missing)
- df.info() : gives the summary of : df data type, columns, columns datatype, memory usage
- df.shape : prints a tuple of configuration of shape of data i.e ( rows, columns )
- df.describe() : prints a numerical statistical summary  of all the numerical columns.
  stats visible are : count, mean, std, min, max,25%, 50%, 75%(25% means this is the data where 25% of values are less than or equal to) 
- df.columns : prints all the columns name
- df.nunique : prints the count of unique rows in each column

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("4_raw_data.csv")
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [3]:
df.head(3)   # prints n rows from starting of the data

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000

In [4]:
df.tail()   # print n rows from ending of the data

   ID    Name  Age Department  Salary
5   6   Frank   29    Finance   50000
6   7   Grace   41         HR   82000
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10   Julia   30    Finance   60000

In [5]:
df.sample(2)  # prints each time n random row of data

   ID   Name  Age Department  Salary
4   5    Eva   38         IT   65000
5   6  Frank   29    Finance   50000

In [6]:
df.info()  # print  overall datatype, column and columns datatype, memory usage

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

In [7]:
 df.shape  # print the shape or configuration (row or column of data type)

(10, 5)

In [8]:
df.describe()  # prints the numerical statistical summary of all the numerical columns

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000

In [9]:
df.index  # prints all the indices corresponding to each row

RangeIndex(start=0, stop=10, step=1)

In [10]:
df.columns   # prints all the column header names

Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='object')

In [11]:
df.nunique()   # print the count of unique row in each column

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64