# Data Cleaning Using Pandas

## Handling Missing Values :
- all the changes executed on the copy so changes does not affect the original data 
- df.isnull() or isna()   : prints the table will 'True' at those position whose values are missing
- df.isnull().sum() or isna().sum() : prints column wise the count of missing values in each column.
- df.dropna() or dp.dropna(axis=1) : removes the entire row or column respectively where a null value exists
- df.fillna(value)  : assign the specified value to each empty cell
- df.ffill() : from top to bottom of a column empty cell is filled by the last encountered not-null value
- df.bfill() : from bottom to top of a column empty cell is filled by the last encountered not-null value (if first element is missing then NaN is assigned or preserved)

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("4_4_persons_raw_data.csv")
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [3]:
df.isnull()   # prints True at those positions where values are missing

       id   name    age  country  gender  income
0   False  False  False    False   False   False
1   False  False  False    False   False   False
2   False  False   True    False   False   False
3   False  False   True    False   False   False
4   False  False  False    False   False    True
5   False  False  False    False   False   False
6   False   True  False    False   False   False
7   False  False  False     True   False   False
8   False  False  False    False   False   False
9   False  False   True    False   False   False
10  False  False  False    False    True   False

In [4]:
df.isna().sum()   # prints column wise the count of missing values in each column

id         0
name       1
age        3
country    1
gender     1
income     1
dtype: int64

In [5]:
df.dropna()    # prints the row whose every cell is not null

   id        name   age country  gender   income
0   1    John Doe  29.0     USA    Male  55000.0
1   1    John Doe  29.0     USA    Male  55000.0
5   5      Li Wei  27.0   China    Male  51000.0
8   8  Rachel Lee  29.0     USA  Female  62000.0

In [8]:
df.dropna(axis=1)   # prints the only columns whose every cell is not null

    id
0    1
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10

In [9]:
df.fillna(0)   # fills each empty cell with specified value

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   0.0  Canada   Female  62000.0
3    3          Alex   0.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      0.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6             0  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0       0     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   0.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA        0  58000.0

In [13]:
cleaned_data =  df.copy()
age_mean = cleaned_data["age"].mean()   # chaining mean function to filtered age column to calculate mean
cleaned_data = cleaned_data["age"].fillna(age_mean)   # assigning the age column's empty value the mean of age to get consistent data of age column 
cleaned_data

0     29.00
1     29.00
2     32.75
3     32.75
4     34.00
5     27.00
6     45.00
7     38.00
8     29.00
9     32.75
10    31.00
Name: age, dtype: float64

In [14]:
df.ffill()   # from top to bottom of column the empty cells are filled with the last encountered not-null value

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  29.0  Canada   Female  62000.0
3    3          Alex  29.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  47000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6        Li Wei  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0   India     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  29.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA     Male  58000.0

In [15]:
df.bfill()  # from bottom to top in a column the empty cells are filled with the last encountered not-null value

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

## Handling the duplicate values : 
- df.duplicated() : returns True for the row with duplicate value (second time True is returned , first time False is returned
if checked on entire table -> if each cell of more than one row are same then those rows are duplicate rows  
- df[[[set_of_column]].duplicated() : checks and return True if all the cells in specified columns for a row is exactly same.

In [17]:
df.duplicated()   # all cells of more than one row must be same for True to be returned

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [20]:
df[["country", "gender"]].duplicated()  # selectedcolumns cells need to be same for more than one row for True to be returned

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool