# Feature Engneering
- df["column_name"].apply(func) : is used to apply a function on basis of specified column values and storing the output into new column
- df["column_name"].map(dictionary) : map the old value with a new value
- df.assign(new_income = df[column] * some changes or operations) : creates a new column(not written in quotes) of specified name by assigning the a specified value
- df["column_name"].replace(old, new) : replace specified old data of the column to new data of the column

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("4_4_persons_raw_data.csv")
df2 =  df.copy()
# lambda function are written with lambda then a variable with colon then body of function is defined note value for if conditon is written before if
df2["tax"] = df2["income"].apply(lambda x : "20%" if x >= 60000 else "10%")

In [3]:
gender_map = {
    "Male" : "M", "Female" : "F", "Unknown":"U"
}
# gender_map
df2["gender"] =  df2["gender"].map(gender_map)    # maps the old value to new value

In [4]:
df2 = df2.assign(new_income = df['income']*1.1)     # creates a new column with the specified name(not written string)by assigning the specified value

In [5]:
df2["country"] = df2["country"].replace("USA", "US")  # replace the old value with the new value

In [6]:
df2

    id          name   age country gender   income  tax  new_income
0    1      John Doe  29.0      US      M  55000.0  10%     60500.0
1    1      John Doe  29.0      US      M  55000.0  10%     60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN      US      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0      US    NaN  58000.0  10%     63800.0

## Data Transformation
- df2.columns = ["...columns_names..."] : changes all column values with the hard coded list
- df2.rename(columns={"column_old_name":"column_new_name"}) : rename the column with specified column and their name through mapping with a  dictionary
- df2.rename(index={old_vale:new_vale})  :  index could also be changed with mapping dictionary specifying old value and new value
- df2.[column_ name].replace("old_name" : "new_name") : replaces the row name to new row name for a specified column
- df2.sort_values(column_name, ascending=True) or df2.sort_values([...column_names...], ascending=False) :
  sort the entire table on the basic of specified column (if columns then first to last preferences)
- df2.reset_index(drop=False{optional}) : resets the indexing from 0 to last and also preserve the old indices by creating a new column named 'index', (drop=True) stop the preserving of old indices
- df2.sort_index() : sort the table according to the indices values
- df2["column"].rank() : gives ranking (lowest to highest) on the basis of specified column and in case of clash average is assigned
- df2["column"].rank(ascending=False, method="dense or min or max") : ascending=True gives rank from 1 to n And method=dense make ranking in whole numbers and no gap should be there if method is 'dense'.
- reorder columns :  df[[column_reorder_list]]  : changes the order of columns.

In [7]:
df2.columns = ["ID", "Name", "Age", "Country", "Gender", "Income", "Tax", "New_Income"]   # hard coding the changed name in a list
df2 = df2.rename(columns={"Income":"Salary", "New_Income":"New_Salary"})   # changs the column names through mapping with a dictionary
df2.rename(index={1:"First"})   # df.rename() : could change column and index only

       ID          Name   Age Country Gender   Salary  Tax  New_Salary
0       1      John Doe  29.0      US      M  55000.0  10%     60500.0
First   1      John Doe  29.0      US      M  55000.0  10%     60500.0
2       2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
3       3          Alex   NaN      US      U  47000.0  10%     51700.0
4       4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN
5       5        Li Wei  27.0   China      M  51000.0  10%     56100.0
6       6           NaN  45.0   India      F  73000.0  20%     80300.0
7       7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8       8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
9       9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10     10   Emily Davis  31.0      US    NaN  58000.0  10%     63800.0

In [8]:
df2['Name'] = df2['Name'].fillna("Mihir Gupta")
df2['Name'] = df2['Name'].replace("Jane Smith", "Joey Smith")

In [9]:
df2

    ID          Name   Age Country Gender   Salary  Tax  New_Salary
0    1      John Doe  29.0      US      M  55000.0  10%     60500.0
1    1      John Doe  29.0      US      M  55000.0  10%     60500.0
2    2    Joey Smith   NaN  Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN      US      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0
6    6   Mihir Gupta  45.0   India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0      US    NaN  58000.0  10%     63800.0

In [10]:
df2['Salary'] = df2['Salary'].fillna(df2['Salary'].mean())
df2['New_Salary'] = df2['New_Salary'].fillna(df2['New_Salary'].mean())
df2.sort_values("Salary")
df2['Age'] = df2['Age'].fillna(df2['Age'].mean())
df2 = df2.sort_values(["Salary", "Age"], ascending=True)

In [11]:
df2.reset_index()   # resets the index from 0 to n and preseves the old indices in a new index column
df2 = df2.reset_index(drop=False)   # if drop=True the new index column for preserving the index is droped

In [15]:
df2

    index  ID          Name    Age Country Gender   Salary  Tax  New_Salary
0       9   9   Carlos Ruiz  32.75  Mexico      M  45000.0  10%     49500.0
1       3   3          Alex  32.75      US      U  47000.0  10%     51700.0
2       5   5        Li Wei  27.00   China      M  51000.0  10%     56100.0
3       0   1      John Doe  29.00      US      M  55000.0  10%     60500.0
4       1   1      John Doe  29.00      US      M  55000.0  10%     60500.0
5       4   4  Maria Garcia  34.00   Spain      F  57600.0  10%     63360.0
6      10  10   Emily Davis  31.00      US      F  58000.0  10%     63800.0
7       8   8    Rachel Lee  29.00      US      F  62000.0  20%     68200.0
8       2   2    Joey Smith  32.75  Canada      F  62000.0  20%     68200.0
9       7   7    Ahmed Khan  38.00     NaN      M  68000.0  20%     74800.0
10      6   6   Mihir Gupta  45.00   India      F  73000.0  20%     80300.0

In [16]:
df2['Gender']= df2['Gender'].fillna('F')
df2.sort_index()    # sort the index

    index  ID          Name    Age Country Gender   Salary  Tax  New_Salary
0       9   9   Carlos Ruiz  32.75  Mexico      M  45000.0  10%     49500.0
1       3   3          Alex  32.75      US      U  47000.0  10%     51700.0
2       5   5        Li Wei  27.00   China      M  51000.0  10%     56100.0
3       0   1      John Doe  29.00      US      M  55000.0  10%     60500.0
4       1   1      John Doe  29.00      US      M  55000.0  10%     60500.0
5       4   4  Maria Garcia  34.00   Spain      F  57600.0  10%     63360.0
6      10  10   Emily Davis  31.00      US      F  58000.0  10%     63800.0
7       8   8    Rachel Lee  29.00      US      F  62000.0  20%     68200.0
8       2   2    Joey Smith  32.75  Canada      F  62000.0  20%     68200.0
9       7   7    Ahmed Khan  38.00     NaN      M  68000.0  20%     74800.0
10      6   6   Mihir Gupta  45.00   India      F  73000.0  20%     80300.0

In [29]:
df2["ranking"] = df2["Salary"].rank()   # gives ranks accroding to the specified column and clashes are given average of logical ranks
df2["ranking"] = df2["Salary"].rank(ascending=True, method="dense")   # dense gives the whole number and maintains no gap in ranking

In [31]:
df2

,index,ID,Name,Age,Country,Gender,Salary,Tax,New_Salary,ranking
0,9,9,Carlos Ruiz,32.75,Mexico,M,45000.0,10%,49500.0,1.0
1,3,3,Alex,32.75,US,U,47000.0,10%,51700.0,2.0
2,5,5,Li Wei,27.00,China,M,51000.0,10%,56100.0,3.0
3,0,1,John Doe,29.00,US,M,55000.0,10%,60500.0,4.0
4,1,1,John Doe,29.00,US,M,55000.0,10%,60500.0,4.0
5,4,4,Maria Garcia,34.00,Spain,F,57600.0,10%,63360.0,5.0
6,10,10,Emily Davis,31.00,US,F,58000.0,10%,63800.0,6.0
7,8,8,Rachel Lee,29.00,US,F,62000.0,20%,68200.0,7.0
8,2,2,Joey Smith,32.75,Canada,F,62000.0,20%,68200.0,7.0
9,7,7,Ahmed Khan,38.00,NaN,M,68000.0,20%,74800.0,8.0
10,6,6,Mihir Gupta,45.00,India,F,73000.0,20%,80300.0,9.0

In [35]:
# df2[[column_reordered_name_list]] : reorders the list of columns 
df2[["index", "ID", "Name", "Age", "Country", "Gender", "Salary", "New_Salary", "Tax", "ranking"]]

,index,ID,Name,Age,Country,Gender,Salary,New_Salary,Tax,ranking
0,9,9,Carlos Ruiz,32.75,Mexico,M,45000.0,49500.0,10%,1.0
1,3,3,Alex,32.75,US,U,47000.0,51700.0,10%,2.0
2,5,5,Li Wei,27.00,China,M,51000.0,56100.0,10%,3.0
3,0,1,John Doe,29.00,US,M,55000.0,60500.0,10%,4.0
4,1,1,John Doe,29.00,US,M,55000.0,60500.0,10%,4.0
5,4,4,Maria Garcia,34.00,Spain,F,57600.0,63360.0,10%,5.0
6,10,10,Emily Davis,31.00,US,F,58000.0,63800.0,10%,6.0
7,8,8,Rachel Lee,29.00,US,F,62000.0,68200.0,20%,7.0
8,2,2,Joey Smith,32.75,Canada,F,62000.0,68200.0,20%,7.0
9,7,7,Ahmed Khan,38.00,NaN,M,68000.0,74800.0,20%,8.0
10,6,6,Mihir Gupta,45.00,India,F,73000.0,80300.0,20%,9.0