# Group by And Aggregation
- grouby(coumn_name) : forms rows as group of values of the specified column but we need a aggregation_funtion() to have some implementation on the groups
- aggregation operation could be : [column_name].min(), .max(), .mean(), .sum() ,.count()
- df.groupby('column_name')[column_name].aggregation_function()
- [column_name].agg([...aggregate_operations...]) or aggregate() : this function is used for implemenation of more than one aggregate operation on the specified column
- df.agg(column_name1=aggregate_operation1, column_name2=aggregate_operation2):assigns specified names to the aggregation operations on entire table
- df.agg(specified_name1=(column_name1,aggregate_operation), specified_name2=(column_name1, aggregation_operation))

In [12]:
import pandas as pd

In [13]:
df = pd.read_csv("4_5_Transformed_Data.csv")

In [14]:
df2 = df.copy()
df2

,index,Name,Age,Country,Gender,Salary,Tax,New_Salary,ranking,ID
0,9,Carlos Ruiz,32.75,Mexico,M,45000.0,10%,49500.0,1.0,9
1,3,Alex,32.75,US,U,47000.0,10%,51700.0,2.0,3
2,5,Li Wei,27.00,China,M,51000.0,10%,56100.0,3.0,5
3,0,John Doe,29.00,US,M,55000.0,10%,60500.0,4.0,1
4,1,John Doe,29.00,US,M,55000.0,10%,60500.0,4.0,1
5,4,Maria Garcia,34.00,Spain,F,57600.0,10%,63360.0,5.0,4
6,10,Emily Davis,31.00,US,F,58000.0,10%,63800.0,6.0,10
7,8,Rachel Lee,29.00,US,F,62000.0,20%,68200.0,7.0,8
8,2,Joey Smith,32.75,Canada,F,62000.0,20%,68200.0,7.0,2
9,7,Ahmed Khan,38.00,India,M,68000.0,20%,74800.0,8.0,7
10,6,Mihir Gupta,45.00,India,F,73000.0,20%,80300.0,9.0,6

In [18]:
df2.groupby('Country')['Salary'].mean()   # group by specifies which columns value need to be considered for grouping.

Country
Canada    62000.0
China     51000.0
India     70500.0
Mexico    45000.0
Spain     57600.0
US        55400.0
Name: Salary, dtype: float64

In [19]:
df2.groupby('Gender')['Salary'].min()   # [column_name] decides which column need to be considered for implementation of aggregation function.

Gender
F    57600.0
M    45000.0
U    47000.0
Name: Salary, dtype: float64

In [20]:

#['column_name'] aggregate() or agg(): to apply many aggregate operations on same column of a data of gnerated by a groupby function.
df.groupby('Country')['Salary'].agg(["mean", "min", "max", "count", "sum"])

            mean      min      max  count       sum
Country
Canada   62000.0  62000.0  62000.0      1   62000.0
China    51000.0  51000.0  51000.0      1   51000.0
India    70500.0  68000.0  73000.0      2  141000.0
Mexico   45000.0  45000.0  45000.0      1   45000.0
Spain    57600.0  57600.0  57600.0      1   57600.0
US       55400.0  47000.0  62000.0      5  277000.0

In [23]:
# renaming of the column could be done by writing {   name="aggregate_operation"    }
df.groupby('Country')['Salary'].agg(Avg_Salary="mean", Min_Salary="min", Max_Salary="max", Country_Count="count", Sum_of_Salary="sum")

         Avg_Salary  Min_Salary  Max_Salary  Country_Count  Sum_of_Salary
Country
Canada      62000.0     62000.0     62000.0              1        62000.0
China       51000.0     51000.0     51000.0              1        51000.0
India       70500.0     68000.0     73000.0              2       141000.0
Mexico      45000.0     45000.0     45000.0              1        45000.0
Spain       57600.0     57600.0     57600.0              1        57600.0
US          55400.0     47000.0     62000.0              5       277000.0

In [16]:
df2

,index,Name,Age,Country,Gender,Salary,Tax,New_Salary,ranking,ID
0,9,Carlos Ruiz,32.75,Mexico,M,45000.0,10%,49500.0,1.0,9
1,3,Alex,32.75,US,U,47000.0,10%,51700.0,2.0,3
2,5,Li Wei,27.00,China,M,51000.0,10%,56100.0,3.0,5
3,0,John Doe,29.00,US,M,55000.0,10%,60500.0,4.0,1
4,1,John Doe,29.00,US,M,55000.0,10%,60500.0,4.0,1
5,4,Maria Garcia,34.00,Spain,F,57600.0,10%,63360.0,5.0,4
6,10,Emily Davis,31.00,US,F,58000.0,10%,63800.0,6.0,10
7,8,Rachel Lee,29.00,US,F,62000.0,20%,68200.0,7.0,8
8,2,Joey Smith,32.75,Canada,F,62000.0,20%,68200.0,7.0,2
9,7,Ahmed Khan,38.00,India,M,68000.0,20%,74800.0,8.0,7
10,6,Mihir Gupta,45.00,India,F,73000.0,20%,80300.0,9.0,6

In [26]:
df2.groupby('Country').agg({  # .agg({})
    'Salary':"mean",
    'Age':"min"
})

          Salary    Age
Country
Canada   62000.0  32.75
China    51000.0  27.00
India    70500.0  38.00
Mexico   45000.0  32.75
Spain    57600.0  34.00
US       55400.0  29.00

In [29]:
df2.groupby('Country').agg(
    Avg_Salary=('Salary',"max"),
    Min_Age=('Age',"min")
)

         Avg_Salary  Min_Age
Country
Canada      62000.0    32.75
China       51000.0    27.00
India       73000.0    38.00
Mexico      45000.0    32.75
Spain       57600.0    34.00
US          62000.0    29.00