## Merge function:
on : decides which column will be considered for joining the two table;   how : decides the way of joining inner(by default), left, right, outer
- pd.merge("column_name1","column_name2", on="column_name")  # by defult inner join which means only common value in both table forms the new table
- pd.merge("column_name1","column_name", on="column_name", how="left"  ) : how = "way_of_join" , on="column_name":decides whicih column to consider for joining
- inner: only common existing value are the part of joined data
- left/right: all the data points of left/right forms the table and NaN values are given to right/left table unknown values
- outer: all the values of the of both the table forms the new table and un

In [2]:
import pandas as pd

In [5]:
df_customers = pd.DataFrame({
    "customer_id" : [1,2,3,4],
    "name" : ["Adam", "Bob", "Charlie", "DAve"]
})

In [6]:
df_customers

   customer_id     name
0            1     Adam
1            2      Bob
2            3  Charlie
3            4     DAve

In [8]:
df_orders = pd.DataFrame({
    "order_id" : [101, 102, 103, 104],
    "customer_id" : [2,1,4,5],
    "amount" : [250,120,300,180]
})

In [9]:
df_orders

   order_id  customer_id  amount
0       101            2     250
1       102            1     120
2       103            4     300
3       104            5     180

In [10]:
pd.merge(df_customers, df_orders, on="customer_id")  #

   customer_id  name  order_id  amount
0            1  Adam       102     120
1            2   Bob       101     250
2            4  DAve       103     300