In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

# Data Science
## Step involved
- Define the Problem
- Data Collection
- Exploratory Data Analysis (EDA)
- Data Cleaning And Pre-Processing
- Feature Engineering
- Modeling
- Evaluation
- Fine Tuning
- Deployment
- Maintainence

## Exploratory Data Analysis (EDA)
- Extract Pattern from Data
- Load and Structure Data
- Clean Data
- Statistical Summary
- Basic Visualization

# Pandas' Datastructure : Series and Data Frame
- Series and DataFrame are classes
- Series : is a 1-D Labelled Array
- DataFrame : is a 2-D Labelled Array
- Note : DataFrame is collection of many different vertical Series
- These Pandas' DataStructure understand the data and could arrange headers and row data by themselves with proper labeling at each row.
- index : position    but    label : named index
- labeled are defined in index parameter index = [values]  (labeled is assigned thourgth the parameter label)
- s.index : returns the list of all the labels (not index),    [Note : Label are named Index]

In [2]:
import pandas as pd

## Series and Its Properties
- 1-D labelled Array (vertically visualized)
- for any operation between different Series the label must be same else not desired operations is not possible
- Homogenous and Vectorization
- Handle missing values with NaN (same as python : None)
- mutable values but immutable size   (if size is altered than a new copy of series is created)
- .drop(index/label)  : creates a copy of series  with the removed value of the specified index

In [3]:
# Series
s = pd.Series([11,22,55,44,33], index=["AA", "BB", "CC", "DD", "EE"])   # label is assigned as a list in index parameter 
print(s)
print(s.dtype)
print(f"The value at position 1 is : {s[1]}")
print(f"The label 'CC' has beeen assigned to the value : {s['CC']}")    # through labels value could be extracted
print(s.index)    # returns the list of all the labels(named index)

ss = pd.Series([77,88,99,110,121], index=["AA", "BB", "CC", "DD", "EE"])   # for any operation between Series the label must be same else not possible
print(s + ss)

sx = s.drop("AA")      # size is immutable so copy of series is created with droped value
print(s)
print(sx)

AA    11
BB    22
CC    55
DD    44
EE    33
dtype: int64
int64
The value at position 1 is : 22
The label 'CC' has beeen assigned to the value : 55
Index(['AA', 'BB', 'CC', 'DD', 'EE'], dtype='object')
AA     88
BB    110
CC    154
DD    154
EE    154
dtype: int64
AA    11
BB    22
CC    55
DD    44
EE    33
dtype: int64
BB    22
CC    55
DD    44
EE    33
dtype: int64

C:\Users\mihir\AppData\Local\Temp\ipykernel_12752\1128814568.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"The value at position 1 is : {s[1]}")

## DataFrame And its Properties
- Its datatype is 'pandas.core.frame.DataFrame'
- pd.DataFrame(collection, columns=[values])   : columns parameter assign labels to each column
- df.index : returns the row labels in form of RangeIndex with start, stop, step parameters
- df.columns : returns the column labels

In [4]:
# dictionary with list inside
info = {
    "Name" : ["Mihir", "Vaishali", "Divyansh"],
    "Age" : [23,22,23],
    "CGPA" : [9.8, 8.98, 8.6]
}
df = pd.DataFrame(info)
print(df)
print(type(df))
print(df.index)
print(df.columns)

       Name  Age  CGPA
0     Mihir   23  9.80
1  Vaishali   22  8.98
2  Divyansh   23  8.60
<class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Age', 'CGPA'], dtype='object')

In [5]:
df

       Name  Age  CGPA
0     Mihir   23  9.80
1  Vaishali   22  8.98
2  Divyansh   23  8.60

In [6]:
# List with List and another parameter columns for the column labels(headers)
df1 = pd.DataFrame([["Mihir",  21], ["Vaishali", 20], ["Divyansh", 22]], columns=["Name", "Age"])
print(df1)
print()
# numpy array
import numpy as np
np_arr = np.array([[1,2,3], [4,5,6]])
df2 = pd.DataFrame(np_arr, columns=["A","B","C"])    # labels are passed as list in columns parameter
print(df2)

       Name  Age
0     Mihir   21
1  Vaishali   20
2  Divyansh   22

   A  B  C
0  1  2  3
1  4  5  6

In [7]:
df

       Name  Age  CGPA
0     Mihir   23  9.80
1  Vaishali   22  8.98
2  Divyansh   23  8.60

In [8]:
df2

   A  B  C
0  1  2  3
1  4  5  6

# Loading and Extracting Files
-  pd.read_csv("file_name.ext") : is used to load the csv file  
-  pd.read_json("file_name.ext") : is used to load the json file  
-  pd.read_excel("file_name.ext") : is used to load the excel file  
-  pd.read_sql("file_name.ext") : is used to load the sql file

In [9]:
df1 = pd.read_csv("4_raw_data.csv")
print(df1)

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [10]:
df1

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [11]:
df2 = pd.read_json("4_raw_data.json")
print(df2)

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [12]:
df2

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000