# DataFrame Methods(Operations)
- df.head(n) : print n rows of data (by defualt 5 rows if n is missing)
- df.tail(n) : print n rows of data (by defualt 5 rows if n is missing)
- df.sample(n) : print each time n random row of the data (by default 1 row if n is missing)
- df.info() : gives the summary of : df data type, columns, columns datatype, memory usage
- df.shape : prints a tuple of configuration of shape of data i.e ( rows, columns )
- df.describe() : prints a numerical statistical summary  of all the numerical columns.
  stats visible are : count, mean, std, min, max,25%, 50%, 75%(25% means this is the data where 25% of values are less than or equal to) 
- df.columns : prints all the columns name
- df.nunique : prints the number of unique row in each columns

In [7]:
import pandas as pd

In [8]:
df = pd.read_csv("raw_data.csv")
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [10]:
df.head(3)   # prints n rows from starting of the data

   id        name   age country  gender   income
0   1    John Doe  29.0     USA    Male  55000.0
1   1    John Doe  29.0     USA    Male  55000.0
2   2  Jane Smith   NaN  Canada  Female  62000.0

In [11]:
df.tail()   # print n rows from ending of the data

    id         name   age country  gender   income
6    6          NaN  45.0   India  Female  73000.0
7    7   Ahmed Khan  38.0     NaN    Male  68000.0
8    8   Rachel Lee  29.0     USA  Female  62000.0
9    9  Carlos Ruiz   NaN  Mexico    Male  45000.0
10  10  Emily Davis  31.0     USA     NaN  58000.0

In [16]:
df.sample(2)  # prints each time n random row of data

   id          name   age country  gender   income
4   4  Maria Garcia  34.0   Spain  Female      NaN
6   6           NaN  45.0   India  Female  73000.0

In [17]:
df.info()  # print  overall datatype, column and columns datatype, memory usage

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       11 non-null     int64
 1   name     10 non-null     object
 2   age      8 non-null      float64
 3   country  10 non-null     object
 4   gender   10 non-null     object
 5   income   10 non-null     float64
dtypes: float64(2), int64(1), object(3)
memory usage: 660.0+ bytes

In [20]:
 df.shape  # print the shape or configuration (row or column of data type)

(11, 6)

In [21]:
df.describe()  # prints the numerical statistical summary of all the numerical columns

              id        age        income
count  11.000000   8.000000     10.000000
mean    5.090909  32.750000  57600.000000
std     3.176619   6.065123   8896.940798
min     1.000000  27.000000  45000.000000
25%     2.500000  29.000000  52000.000000
50%     5.000000  30.000000  56500.000000
75%     7.500000  35.000000  62000.000000
max    10.000000  45.000000  73000.000000

In [22]:
df.columns

Index(['id', 'name', 'age', 'country', 'gender', 'income'], dtype='object')

In [23]:
df.nunique'9

AttributeError: 'DataFrame' object has no attribute 'unique'